[package]
name = "enumset-rs"
version = "0.1.0"
authors = ["askepen <aske@daske.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
